package com.material.zhihu;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.material.zhihu.StoryRecord;

import com.material.zhihu.StoryRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storyRecordDaoConfig;

    private final StoryRecordDao storyRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storyRecordDaoConfig = daoConfigMap.get(StoryRecordDao.class).clone();
        storyRecordDaoConfig.initIdentityScope(type);

        storyRecordDao = new StoryRecordDao(storyRecordDaoConfig, this);

        registerDao(StoryRecord.class, storyRecordDao);
    }
    
    public void clear() {
        storyRecordDaoConfig.getIdentityScope().clear();
    }

    public StoryRecordDao getStoryRecordDao() {
        return storyRecordDao;
    }

}
